# Example config for npm-sync
# Place a copy as 'config.yml' and edit values.
source:
  host: "http://npm-origin.lan:81"
  username: "admin@example.com"
  password: "changeme"

destinations:
  - host: "http://npm-dest.lan:81"
    username: "admin@example.com"
    password: "changeme"

# Interval in hours between sync runs
interval_hours: 12

# Behavior
mirror: true        # if true, will delete in destination what doesn't exist in source
dry_run: false      # if true, will only print actions without performing them
log_level: "info"   # debug | info | warning | error
